version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-test-upload:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: 
          name: Get UTC Time
          command: pwd && curl "http://worldtimeapi.org/api/timezone/etc/utc"
      - run:
          name: Install Java JRE
          command: sudo apt update && sudo apt install default-jre -y
      - run:
          name: Download allure commandline
          command: mkdir -p /home/circleci/project/ && wget https://github.com/allure-framework/allure2/releases/download/2.17.1/allure-2.17.1.zip && unzip allure*.zip && rm allure*.zip && mv allure-2.* /home/circleci/project/allure
      - run:
          name: Run tests
          command: pytest || true
      - run:
          name: Run tests with pytest; html extension
          command: pytest --html=test_result_report.html --self-contained-html || true
      - run:
          name: Run tests with pytest; txt extension
          command: pytest -m fruits > test_result_03.txt
      - run:
          name: Run tests with allure
          command: pytest --alluredir=test_result_alluredir || true
      - run:
          name: Get Previous Execution History
          command: |
            curl -H "Circle-Token: $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/github/jim-mode/qa-automation-ci-cd/latest/artifacts \
            | grep -o 'https://[^"]*' \
            | grep 0/history.zip \
            | wget --verbose --header "Circle-Token: $CIRCLE_TOKEN" --input-file -
      - run:
          name: Extract History
          command: unzip history.zip && rm history.zip && mv history test_result_alluredir || true
      - run:
          name: Generate allure html report
          command: /home/circleci/project/allure/bin/./allure generate test_result_alluredir
      - run:
          name: Zip Allure History
          command: cd ./allure-report/ && zip -r history.zip history
      - store_artifacts:
          path: test_result_report.html
          destination: html_report
      - store_artifacts:
          path: allure-report
          destination: allure-report
      - store_artifacts:
          path: test_result_03.txt
      - store_artifacts:
          path: test_result_alluredir

workflows:
  main-ci-workflow:
    jobs:
      - build-test-upload:
          filters:
            branches:
              only:
                - main
                - /release.*/
                - /feature.*/
  nightly-ci-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build-test-upload
