version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-test-upload:
    docker:
      - image: nojson/cimg_py:chrome-96
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: 
          name: Get UTC Time
          command: pwd && curl "http://worldtimeapi.org/api/timezone/etc/utc" || true
      - run:
          name: Run tests with allure
          command: pytest --alluredir=test_result_alluredir || true
      - run:
          name: Get Previous Execution History
          command: |
            curl -H "Circle-Token: $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/github/jim-mode/ci-test-automation/latest/artifacts \
            | grep -o 'https://[^"]*' \
            | grep allure-history.zip \
            | wget --verbose --header "Circle-Token: $CIRCLE_TOKEN" --input-file - || true
      - run:
          name: Extract History
          command: unzip allure-history.zip && rm allure-history.zip && mv history test_result_alluredir || true
      - run:
          name: Generate allure html report
          command: /home/circleci/allure/bin/./allure generate test_result_alluredir
      - run:
          name: Zip Allure History
          command: cd ./allure-report/ && zip -r history.zip history
      - store_artifacts:
          path: allure-report
          destination: allure-report
      - store_artifacts:
          path: test_result_report.html
          destination: html_report
      - store_artifacts:
          path: test_result_alluredir
      - store_artifacts:
          path: google_search.png
      - store_artifacts:
          path: allure-report/history.zip
          destination: allure-history.zip
workflows:
  main-ci-workflow:
    jobs:
      - build-test-upload:
          filters:
            branches:
              only:
                - main
                - /release.*/
                - /feature.*/
  nightly-ci-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build-test-upload
