name: Github Action with pytest artifacts and cron
on:
  push:
    branches:
      - main
      - 'release/**'
      - 'feature/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  get-time:
    runs-on: ubuntu-latest
    steps:
      - name: Get UTC Time
        run: curl "http://worldtimeapi.org/api/timezone/etc/utc"

      - name: Get Central Time
        run: curl "http://worldtimeapi.org/api/timezone/America/Chicago"

  build-test-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest; html extension
        id: full_run_01
        run: pytest --html=test_result_report.html --self-contained-html
        continue-on-error: true # ignore the random fail steps

      - name: Run tests with pytest; txt extension
        id: full_run_02
        run: pytest > test_result_default.txt
        continue-on-error: true # ignore the random fail steps

      - name: Run tests with pytest; txt extension
        id: run_test_01
        run: pytest hello_test.py -k test_capitalize_string_01 > test_result_01.txt

      - name: Run tests with pytest; txt extension
        id: run_test_02
        run: pytest hello_test.py::TestCap::test_capitalize_string_02 > test_result_02.txt

      - name: Run tests with pytest; log extension
        id: run_test_03
        run: pytest -m fruits > test_result_03.log

      - name: Check on failures #sandbox step to ensure at least one test is successful
        if: steps.run_test_01.outcome != 'success' || steps.run_test_02.outcome != 'success' || steps.run_test_03.outcome != 'success'
        run: exit 1

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: code-testing-report
          path: |
            test_result**.log
            test_result**.txt
            test_result**.html
          retention-days: 12
